In [21]:
import numpy as np

Numpy indxing and slicing of vector

---





In [22]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [23]:
arr[9]

np.int64(20)

In [24]:
arr_slice=arr[1:5]
arr_slice

array([12, 13, 14, 15])

In [25]:
arr_Slicie1=arr[4::2]
arr_Slicie1

array([15, 17, 19])

NUMPY INDEXING AND Slicing of MATRIX

---



In [26]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [27]:
arr[4]

array([21, 22, 23, 24, 25])

In [28]:
arr[0,3] #4

np.int64(4)

In [29]:
arr[4,3] #24

np.int64(24)

In [30]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

Practice

---






In [31]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [32]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [33]:
arr[4:,1:3]

array([[22, 23],
       [27, 28]])

In [34]:
arr[4:,3:]

array([[24, 25],
       [29, 30]])

BOOLEAN INDEXING

---



In [35]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [36]:
bool_index= arr % 2 ==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [37]:
arr=arr[bool_index]
arr


array([12, 14, 16, 18, 20])