In [184]:
import numpy as np

Vaalid Sudoku

---



In [185]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [186]:
b=np.sum(s,axis=1)
for i in b:
  if(i==45):
     print("for row it is Valid sudoku")
     break
  else:
    print("Not Sudoku")

for row it is Valid sudoku


In [187]:
b=np.sum(s,axis=1)
for i in b:
  if(i==45):
     print("for Columns it  is Valid sudoku")
     break
  else:
    print("Not Sudoku")

for Columns it  is Valid sudoku


In [188]:
s[0:3,0:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [189]:
s[0:3,3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [190]:
s[0:3,6:9]

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

In [191]:
s

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

Using Python Same as top

In [192]:
for i in range(0,9,3):
  for j in range(0,9,3):
    n=(s[i:i+3,j:j+3])
    print(n.sum())

45
45
45
45
45
45
45
45
45


In [193]:
np.sum(n)

np.int64(45)

General Questions

---



In [194]:
import numpy as np
#   Age|AI|ML
data=np.array([
    [18,88,89],
    [21,91,90],
    [22,90,98],
    [22,65,65],
    [19,88,94]
])

In [195]:
#Get shape of matrix
data.shape

(5, 3)

In [196]:
#Find the avgerge age of student
np.mean(data[:,0])

np.float64(20.4)

In [197]:
# Extract AI marks of all students
data[:,1]

array([88, 91, 90, 65, 88])

In [198]:
#Find the ML Highest Marks
np.max(data[:,2])

np.int64(98)

In [199]:
#Get student of get marks in more than 90 in AI
data[data[:,1]>90]

array([[21, 91, 90]])

In [200]:
data

array([[18, 88, 89],
       [21, 91, 90],
       [22, 90, 98],
       [22, 65, 65],
       [19, 88, 94]])

In [201]:
#Increase AI marks of all student by 5
data[:,1] += 5
data

array([[18, 93, 89],
       [21, 96, 90],
       [22, 95, 98],
       [22, 70, 65],
       [19, 93, 94]])

In [202]:
#Find how many student younger gerther than 19
len(data[data[:,0] < 19])


1

In [203]:
#Calculate the avg marks of each subject (col-wise-mean)
np.mean(data[:,1:],axis=0)

array([89.4, 87.2])

In [204]:
data

array([[18, 93, 89],
       [21, 96, 90],
       [22, 95, 98],
       [22, 70, 65],
       [19, 93, 94]])

In [205]:
#Get data student who score at least 80 in both suject
data[(data[:,1] >=80) & (data[:,2] >=80)]


array([[18, 93, 89],
       [21, 96, 90],
       [22, 95, 98],
       [19, 93, 94]])

In [206]:
data

array([[18, 93, 89],
       [21, 96, 90],
       [22, 95, 98],
       [22, 70, 65],
       [19, 93, 94]])

In [207]:
  #Repalce of ML marks <75 with 0
data[:,2][data[:,2] < 75] = 0
data

array([[18, 93, 89],
       [21, 96, 90],
       [22, 95, 98],
       [22, 70,  0],
       [19, 93, 94]])